version: "3.3"

services:
  db:
    build: 
      context: .
      dockerfile: postgres.Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      #- ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

    networks:
      - default

  app:
    build: .
    env_file: .env
    ports:
      - "5500:5500"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - default


networks:
  default:
    driver: bridge

